import data from "@/data/metrics/constellation-assets.json";
type Lang = "zh" | "en";
const colors = ["#d9ff43", "#6a9eff", "#e7b663", "#ff6c53", "#ba93ed"];
const epoch=(d:string)=>Date.parse(d+"T00:00:00Z");
export default function ConstellationAssets({lang}:{lang:Lang}){
  const zh=lang==='zh', tr=(a:string,b:string)=>zh?a:b;
  const x=(d:string)=>65+(epoch(d)-epoch('2018-01-01'))/(epoch(data.inventoryAsOf)-epoch('2018-01-01'))*790;
  const targets=data.constellations.map(c=>Number(c.planValue.replace(/[^0-9]/g,'')));
  const y=(n:number)=>300-Math.log10(n+1)/Math.log10(20001)*270;
  const tx=(d:string)=>(epoch(d)-epoch('2016-01-01'))/(epoch('2038-01-01')-epoch('2016-01-01'))*100;
  return <section id="constellation-assets" className="constellation-assets" aria-labelledby="constellation-title">
    <div className="constellation-heading"><div><span className="constellation-eyebrow">{tr('02A / 星座资产与申报','02A / FLEETS & FILINGS')}</span><h3 id="constellation-title">{tr('在轨规模，正在如何增长','How orbital fleets are growing')}</h3></div><p>{tr('在轨数量估算 · 共用对数纵轴','Estimated orbital counts · shared logarithmic axis')}<br/>{data.inventoryAsOf}</p></div>
    <div className="fleet-chart-panel"><div className="fleet-legend">{data.constellations.map((c,i)=><div key={c.id}><i style={{background:colors[i]}}/><b>{zh?c.nameZh:c.nameEn}</b><strong>{c.inOrbit.toLocaleString()}</strong><span>{tr('目标参照','Target reference')} {c.planValue}</span></div>)}</div>
      <div className="fleet-chart-scroll"><svg viewBox="0 0 900 345" role="img" aria-label={tr('五个星座共同数量增长图，实线库存、虚线目标，对数轴','Shared five-fleet growth chart; solid inventory, dashed targets; logarithmic axis')}>
        {[0,10,100,1000,10000,20000].map(n=><g key={n}><line x1="65" x2="855" y1={y(n)} y2={y(n)} stroke="#454954"/><text x="55" y={y(n)+5} textAnchor="end" fill="#c0c3ca" fontSize="14">{n.toLocaleString()}</text></g>)}
        {[2018,2020,2022,2024,2026].map(n=><text key={n} x={x(n+'-01-01')} y="330" textAnchor="middle" fill="#c0c3ca" fontSize="15">{n}</text>)}
        {data.constellations.map((c,i)=><g key={c.id}><line x1="65" x2="855" y1={y(targets[i])} y2={y(targets[i])} stroke={colors[i]} strokeDasharray={`${8+i*2} 7`} opacity=".65"><title>{zh?c.nameZh:c.nameEn}: {c.planValue} · {zh?c.planLabelZh:c.planLabelEn}</title></line><polyline points={c.history.slice(0,-1).map(p=>`${x(p.date)},${y(p.inOrbit)}`).join(' ')} fill="none" stroke={colors[i]} strokeWidth="2.5"/><line x1={x(c.history.at(-2)!.date)} y1={y(c.history.at(-2)!.inOrbit)} x2={x(c.asOf)} y2={y(c.inOrbit)} stroke={colors[i]} strokeWidth="2.5" strokeDasharray="4 3"/><circle cx={x(c.asOf)} cy={y(c.inOrbit)} r="4" fill={colors[i]}><title>{c.asOf}: {c.inOrbit}</title></circle></g>)}
      </svg></div></div>
    <p className="constellation-method">{tr('实线：月末库存估算；长虚线：目标参照；末段短虚线：快照来源切换。对数轴用于同时看清大小星座，不表示线性增长速度。千帆 15,000 为远期下限。','Solid: estimated month-end inventory. Long dash: target reference. Short final dash: snapshot source transition. Log scale makes large and small fleets legible, not linear growth rates. Qianfan 15,000 is a lower bound.')}</p>
    <div className="fleet-scope-grid">{data.constellations.map((c,i)=><article key={c.id} style={{borderTopColor:colors[i]}}><h4>{zh?c.nameZh:c.nameEn}</h4><p>{c.operator}</p><strong>{c.planValue}</strong><p>{zh?c.planZh:c.planEn}</p><a href={c.planSourceUrl} target="_blank" rel="noreferrer">{tr('目标来源','Target source')} ↗</a><a href={c.sourceUrl} target="_blank" rel="noreferrer">GCAT · {c.asOf} ↗</a></article>)}</div>
    <p className="constellation-method">{zh?data.historyMethodZh:data.historyMethodEn} {tr('目标性质分别为授权、通知或商业计划，不能相加，也不作为 ITU 完成率分母。原 02A 的其他运营者和通信/导航网络仍在下方保留。','Targets represent authorization, notification or commercial plans: not additive, not ITU completion denominators. Other operators and communications/navigation networks remain below.')}</p>
    <div className="itu-heading"><h4>{tr('ITU：商业星座与具体申报历史','ITU: commercial fleets and filing history')}</h4><p>2016–2038 · {data.ituAsOf}</p></div>
    <p className="itu-explainer">{tr('申报 / 公布 · BIU 频率启用 · 部署 / 报告 · 截止日期分别标记。BIU 不等于首次发射或商业开通；报告收件日也不是实际达成日。','Separate filing/publication, BIU, deployment/report and deadline markers. BIU is not first launch or commercial opening; report receipt is not an achievement date.')}</p>
    <div className="filing-history-scroll" tabIndex={0}><div className="filing-history">
      <div className="filing-axis"><span>{tr('商业名称 → 申报网络','COMMERCIAL NAME → NETWORK')}</span><div>{[2016,2020,2024,2028,2032,2036,2038].map(n=><span key={n} style={{left:tx(n+'-01-01')+'%'}}>{n}</span>)}</div></div>
      {data.filings.map(f=>{const brand=data.constellations.find(c=>c.id===f.constellationId);return <div className="filing-history-row" key={f.id}><div className="filing-identity"><h5>{brand?(zh?brand.nameZh:brand.nameEn):tr('未归属商业星座','Unassigned commercial fleet')}{f.candidate?' ?':''}</h5><p>{brand?.operator??tr('主体待核验','Operator unverified')}</p><a href={f.sourceUrl} target="_blank" rel="noreferrer">{f.network} · {f.administration} ↗</a><small>{f.notificationIds.join(' / ')||tr('版本身份未取得','Version identity unavailable')}</small></div><div className="filing-event-lanes">{f.events.map((e,i)=><a key={e.date+e.labelEn+i} className={'filing-event event-'+e.kind} href={e.sourceUrl} target="_blank" rel="noreferrer" style={{left:tx(e.date)+'%',top:16+i*49}}><b>{zh?e.labelZh:e.labelEn}</b><span>{e.date}</span><i/></a>)}<div className="filing-undated" style={{marginTop:Math.max(70,f.events.length*49+16)}}>{f.milestones.filter(m=>!m.date&&m.status).map(m=>`${m.stage}: ${m.status==='Met'?tr('已达标 · 日期待核验','met · date unverified'):m.status==='As Received'?tr('已收件 · 日期待核验','received · date unverified'):m.status}`).join(' / ')|| (zh?f.noteZh:f.noteEn)||tr('暂无已达成日期','No achievement dates available')}</div></div></div>})}
    </div></div>
    <p className="constellation-method">{tr('CTC-1 / CTC-2 已收录 2025 年申报与 2026 年公布日期；十万级数量及商业主体尚待原始技术通知核验，不归入国网或千帆。Starlink Gen3 十万级申请线索指向 2026 年，未作为已批准目标绘入本图。未公开的完成日期保持未知。','CTC-1 / CTC-2 include 2025 receipt and 2026 publication dates. Six-figure counts and operators await technical notices; neither is allocated to Guowang/Qianfan. The six-figure Starlink Gen3 application lead points to 2026 and is not plotted as an approved target. Undisclosed achievement dates remain unknown.')}</p>
  </section>;
}
