export default function ITUStages({lang}:{lang:'zh'|'en'}) {
  const zh=lang==='zh',tr=(a:string,b:string)=>zh?a:b;
  const stages=[
    ['API / CR',tr('申报与协调','Filing and coordination'),tr('API 提前公布或 CR 协调请求登记技术参数；收件和公布不是批准。具体频率组的有效收件日决定计时，新频段修改可能有新的期限。','API advance publication or CR coordination records technical parameters. Receipt/publication is not approval; effective receipt sets each frequency-group clock. New bands may have a new deadline.')],
    ['BIU',tr('频率实际启用','Bringing into use'),tr('适用的非静止网络须在七年监管期内，由具备相应收发能力的卫星在通知轨道上连续运行 90 天。不是“发射一颗就自动启用”，也不是要求七年内部署完整星座。','Applicable non-GSO assignments must be used within the seven-year period by a capable spacecraft operating in the notified orbit for 90 continuous days. A launch alone is not BIU; full deployment is not required within seven years.')],
    ['M0',tr('初始部署报告','Initial deployment report'),tr('RES35 的初始部署信息报告，通常在七年监管期结束后 30 天内提交；过渡网络另有锚点。M0 不是 BIU 的别名，报告收件也不等于审查达标。','RES35 initial deployment information is normally due within 30 days after the regulatory period; transitional systems use their own anchor. M0 is not another name for BIU, and receipt is not compliance confirmation.')],
    ['M1 → M3',tr('10% → 50% → 100%','10% → 50% → 100%'),tr('适用 RES35 的频段/业务在监管期终点后 +2 / +5 / +7 年达到相应部署比例。按有效通知与频段计数；未达标须依规则削减申报规模，不能用品牌总在轨数认定达标。','For RES35 bands/services, deployment milestones fall +2 / +5 / +7 years after the regulatory limit. Counts apply to effective notifications and bands; shortfalls require reductions under the rules, not a brand-wide fleet percentage.')],
  ];
  return <div className="itu-stage-guide"><h5>{tr('读懂各阶段要求','Reading the regulatory stages')}</h5><div>{stages.map(([code,title,detail])=><article key={code}><b>{code}</b><h6>{title}</h6><p>{detail}</p></article>)}</div><p>{tr('MIFR 是频率指配总登记簿；PART II-S 表示已登记的通知，仍须检查具体指配与审查结果。下表的网络最早申报日期不自动替代频率组计时锚点。','MIFR is the Master International Frequency Register. PART II-S identifies a recorded notice, subject to assignment-level findings. A network’s earliest filing does not automatically replace its frequency-group clock.')} <a href="https://www.itu.int/en/ITU-R/space/Pages/FAQspace.aspx" target="_blank" rel="noreferrer">ITU FAQ ↗</a> · <a href="https://www.itu.int/en/ITU-R/space/Pages/res35main.aspx" target="_blank" rel="noreferrer">RES35 ↗</a></p></div>;
}
