const patterns=[
 {name:'Next Spaceflight',url:'https://nextspaceflight.com/',moduleZh:'01 发射信息',moduleEn:'01 Launch information',useZh:'首要范式：近期任务、最近结果、任务卡片关联火箭、运营商与基地。',useEn:'Primary pattern: upcoming missions, recent outcomes, and mission cards linking vehicle, provider and site.',stateZh:'已用于本版组织与再开发',stateEn:'Applied to this release'},
 {name:'Kevin Ricche · Constellation Tracker',url:'https://www.kevinricche.com/constellations/',moduleZh:'03 在轨资产',moduleEn:'03 Orbital assets',useZh:'品牌摘要、运营商、计划与库存分列，共同增长时间线；不照搬完成率。',useEn:'Fleet summaries, operators, separate plans/inventory and shared growth history; no copied compliance percentages.',stateZh:'已用于星座展示结构',stateEn:'Applied to fleet presentation'},
 {name:'Orbital Radar',url:'https://orbitalradar.com/satellite-internet/qianfan-vs-starlink',moduleZh:'03 在轨资产',moduleEn:'03 Orbital assets',useZh:'同日历与首发日对齐比较、最近90天节奏；借鉴方向，不导入混合口径数字。',useEn:'Calendar versus programme-age comparisons and trailing 90-day pace; not mixed-definition counts.',stateZh:'后续再开发参照，尚未全部实现',stateEn:'Future reference; not fully implemented'},
 {name:'starlink-viz · Fleet Monitor',url:'https://github.com/juliensimon/starlink-viz',moduleZh:'03 在轨资产',moduleEn:'03 Orbital assets',useZh:'壳层填充、状态与生命周期分模块；保留观测与推断边界，不以3D仿真为主界面。',useEn:'Shell fill, status and lifecycle modules; distinguish observations from inference, without a 3D-led interface.',stateZh:'后续资产分析参照',stateEn:'Future asset-analysis reference'},
 {name:'NewSpace Index',url:'https://www.newspace.im/',moduleZh:'03 在轨资产',moduleEn:'03 Orbital assets',useZh:'项目、代际、用途和计划变更的目录组织；已发射不等于当前在轨。',useEn:'Directory organization by project, generation, purpose and plan changes; launched is not in orbit.',stateZh:'目录扩展参照',stateEn:'Directory expansion reference'},
 {name:'ITU Argus',url:'https://www.itu.int/space-argus/',moduleZh:'03 申报关系',moduleEn:'03 Filing relationships',useZh:'申报部署、频率登记与运营主体关联模型；仅参考官方介绍，会员界面未核验。',useEn:'Relationships between reported deployment, frequency registration and operators; public description only, member UI not inspected.',stateZh:'数据关系模型参照，非公开数据接入',stateEn:'Model reference, not public ingestion'}
];
const sources=[
 {name:'GCAT / Jonathan McDowell',url:'https://planet4589.org/space/gcat/',useZh:'当前在轨资产、质量覆盖、2000年以来库存与制造交付；星座统计独立保留快照日期。',useEn:'Current assets, mass coverage, inventory and delivered output since 2000; fleet statistics retain their own snapshot dates.',limitZh:'目录估算不等于运营商遥测；质量存在缺失，不把全部库存当活跃对象。',limitEn:'Catalog estimates are not operator telemetry; mass is incomplete and total inventory is not active-only.'},
 {name:'The Space Devs · Launch Library 2',url:'https://thespacedevs.com/llapi',useZh:'近期与未来任务、发射结果、火箭构型、一级复用以及基地/台位活动。',useEn:'Upcoming/recent missions, outcomes, configurations, stage reuse and observed site/pad activity.',limitZh:'本地快照，非实时；未来时间保留精度，基地活动不等于完整设施普查。',limitEn:'Local snapshots, not real-time; preserve schedule precision, and activity is not a facility census.'},
 {name:'ITU · RES35 / SNL',url:'https://www.itu.int/en/ITU-R/space/Pages/res35main.aspx',useZh:'具体申报组别的收件、公布、BIU、监管锚点与官方部署节点。',useEn:'Receipt, publication, BIU, regulatory anchors and official milestones per filing.',limitZh:'未知日期留空；收件、公布、登记与达标不同，估算在轨数不用于认定合规。',limitEn:'Unknown dates stay null; receipt, publication, registration and compliance differ. Inventory estimates do not establish compliance.'},
 {name:'FCC',url:'https://docs.fcc.gov/public/attachments/DA-26-36A1.pdf',useZh:'美国具体代际的授权、阶段部署要求及豁免；与 ITU 单独追踪。',useEn:'US generation-specific grants, deployment requirements and waivers, tracked separately from ITU.',limitZh:'不同代际、频段与修改单独核验，不按品牌总库存求履约百分比。',limitEn:'Check generations, bands and amendments separately; no whole-brand compliance ratio.'},
 {name:'NASA / ESA / 中国官方项目资料',url:'https://www.nasa.gov/',useZh:'载人、地月资产、任务节点、轨道示意图依据与图像署名；每项原始链接保留在对应卡片。',useEn:'Crewed/cislunar assets, mission milestones, orbit references and image credits; exact sources remain on each card.',limitZh:'项目日期和计划可能调整；示意轨道图不是真实轨道预报。',limitEn:'Plans may change; schematic orbit diagrams are not propagated trajectories.'}
];
export default function SourceReferences({lang}:{lang:'zh'|'en'}){
 const zh=lang==='zh',tr=(a:string,b:string)=>zh?a:b;
 return <div className="source-reference-catalog"><div className="section-heading"><div><p className="section-index">{tr('来源 / 引用 / 再开发参照','SOURCES / ATTRIBUTION / DEVELOPMENT REFERENCES')}</p><h2>{tr('数字从哪里来，展示向谁学习','Where the numbers come from—and the design references')}</h2></div><p>{tr('数据证据与产品范式分开署名。参考不代表合作、背书或数据授权；展示结构由本项目独立实现。','Data evidence and product patterns are attributed separately. References do not imply partnership, endorsement or data permission; this project implements its own interface.')}</p></div>
 <h3>{tr('实际引用的数据与证据','Data and evidence used')}</h3><div className="source-reference-grid">{sources.map(s=><article key={s.name}><span>{tr('数据 / 证据来源','DATA / EVIDENCE')}</span><h4><a href={s.url} target="_blank" rel="noreferrer">{s.name==='NASA / ESA / 中国官方项目资料'?tr('NASA / ESA / 中国官方项目资料','NASA / ESA / Chinese official program sources'):s.name} ↗</a></h4><p>{zh?s.useZh:s.useEn}</p><small>{zh?s.limitZh:s.limitEn}</small></article>)}</div>
 <h3>{tr('展示范式与再开发参照','Presentation patterns and development references')}</h3><div className="source-reference-grid">{patterns.map(s=><article key={s.name}><span>{zh?s.moduleZh:s.moduleEn}</span><h4><a href={s.url} target="_blank" rel="noreferrer">{s.name==='NASA / ESA / 中国官方项目资料'?tr('NASA / ESA / 中国官方项目资料','NASA / ESA / Chinese official program sources'):s.name} ↗</a></h4><p>{zh?s.useZh:s.useEn}</p><small>{zh?s.stateZh:s.stateEn}</small></article>)}</div>
 <div className="source-reference-note"><h4>{tr('本项目模型与仍待接入的数据','Project models and pending data')}</h4><p>{tr('2026–2036 发射与在轨预测是本项目模型：GCAT 同期推算、历史净增外推，以及分别标注的 FCC / 商业 / ITU 条件情景；不是上游机构发布的预测。卡尔达肖夫历史序列仍未逐年接入可审计能源统计。完整单位入轨成本历史也仍有产品样例。','The 2026–2036 launch and orbital projections are project models: GCAT matched-period nowcasting, net-growth extrapolation and separately marked FCC, commercial and ITU conditional scenarios, not forecasts published by those sources. Kardashev history still lacks auditable annual energy input. Complete orbital unit-cost history still includes product samples.')}</p><a href="https://github.com/carolplay/space-race-dashboard" target="_blank" rel="noreferrer">{tr('本项目源码、数据快照与再开发记录','Project source, snapshots and development records')} ↗</a></div>
 </div>;
}
